### PR TITLE
Use compile command instead of build

### PR DESCRIPTION
**Pull request by kdobmayer**

### CODE REVIEW

**Comment by blackjid** [comment]
this is awesome, thanks!

can you please publish the new 1.1.0 to https://github.com/bitrise-io/bitrise-steplib
thanks!

**Comment by viktorbenei** [comment]
@blackjid it's in https://github.com/bitrise-community/steps-cordova-archive/releases/tag/1.1.0

**Comment by viktorbenei** [comment]
ohh, but that's not published in the steplib! got it, sorry! :)

**Comment by blackjid** [comment]
thanks!

**Pull request merged**
